
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-ops

resources:
  - namespace.yaml
#  - sources
#  - cert-manager
#  - nginx
  - kubernetes-dashboard
  #  - cluster-monitoring
