---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      version: ">=1.1.1"
  interval: 180m
  values:
    defaultSettings:
      defaultDataPath: "/storage"
---
