apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fluxv2
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/fluxcd/flux2
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/manifests/monitoring
---