apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 180m
  path: ./manifests/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxv2
    namespace: flux-system
  validation: client