---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: nginx
      version: ">=3.29.0"
  interval: 180m
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
      metrics:
        enabled: "true"
    #        service:
    #          annotations:
    #            prometheus.io/scrape: "true"
    #            prometheus.io/port: "10254"
    defaultBackend:
      enabled: false
      image:
        repository: k8s.gcr.io/defaultbackend-arm64
        tag:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace