---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: sources
      version: ">=v1.3.0"
  interval: 180m
  values:
    installCRDs: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace