apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
    namespace: ops
spec:
    acme:
        # You must replace this email address with your own.
        # Let's Encrypt will use this to contact you about expiring
        # certificates, and issues related to your account.
        email: letsencrypt@k3s-kluster.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            # Secret resource that will be used to store the account's private key.
            name: letsencrypt-production
        # Add a single challenge solver, HTTP01 using nginx
        solvers:
            - http01:
                ingress:
                    class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
    namespace: cert-manager
spec:
    acme:
        # You must replace this email address with your own.
        # Let's Encrypt will use this to contact you about expiring
        # certificates, and issues related to your account.
        email: letsencrypt@k3s-kluster.com
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            # Secret resource that will be used to store the account's private key.
            name: letsencrypt-staging
        # Add a single challenge solver, HTTP01 using nginx
        solvers:
            - http01:
                ingress:
                    class: nginx

